package errors

import (
	"errors"
)

var (
	ErrLoginFailed                = errors.New("login failed, incorrect username or password")
	ErrCouldNotGetAPIVersion      = errors.New("could not get API version")
	ErrCouldNotGetSettings        = errors.New("could not get settings")
	ErrCouldNotSetSettings        = errors.New("could not set settings")
	ErrFailedToGetSession         = errors.New("failed to get session")
	ErrFileNotCreated             = errors.New("file not created")
	ErrCouldNotWriteToFile        = errors.New("could not write to file")
	ErrFileDoesNotExist           = errors.New("file does not exist")
	ErrCouldNotReadFile           = errors.New("could not read file")
	ErrCouldNotSetSession         = errors.New("could not set session")
	ErrCouldNotGetFeed            = errors.New("could not get feed")
	ErrCouldNotGetMediaID         = errors.New("could not get media id")
	ErrCouldNotGetMediaPK         = errors.New("could not get media pk")
	ErrCouldNotGetMediaPKFromCode = errors.New("could not get media pk from code")
	ErrCouldNotGetMediaPKFromURL  = errors.New("could not get media pk from URL")
	ErrCouldNotGetMediaInfoByPk   = errors.New("could not get media info by pk")
	ErrCouldNotGetUserMedias      = errors.New("could not get user medias")
	ErrCouldNotDeleteMedia        = errors.New("could not delete media")
	ErrCouldNotEditMedia          = errors.New("could not edit media")
	ErrAuthorDoesNotExist         = errors.New("could not get media/author")
	ErrCouldNotGetMediaInfo       = errors.New("could not get media info")
	ErrMediaNotLiked              = errors.New("media not liked")
	ErrMediaCouldNotBeUnliked     = errors.New("media could not be unliked")
	ErrCouldNotGetMediaLikers     = errors.New("could not get media likers")
	ErrCouldNotArchiveMedia       = errors.New("could not archive media")
	ErrCouldNotUnArchiveMedia     = errors.New("could not unarchive media")
	ErrCouldNotGetUserFollowers   = errors.New("could not get user's followers")
	ErrCouldNotGetUsersFollowing  = errors.New("could not get users following")
	ErrCouldNotGetUserInfo        = errors.New("could not get user info")
	ErrCouldNotFollowUser         = errors.New("could not follow user")
	ErrCouldNotUnfollowUser       = errors.New("could not unfollow user")
	ErrCouldNotGetUserId          = errors.New("could not get user ID")
	ErrCouldNotGetUsername        = errors.New("could not get username")
	ErrCouldNotRemoveFollower     = errors.New("could not remove follower")
	ErrCouldNotMutePosts          = errors.New("could not mute posts")
	ErrCouldNotUnmutePosts        = errors.New("could not unmute posts")
	ErrCouldNotMuteStories        = errors.New("could not mute stories")
	ErrCouldNotUnMuteStories      = errors.New("could not unmute stories")
	ErrCouldNotDownloadIgtv       = errors.New("could not download igtv")
	ErrCouldNotGetUserStory       = errors.New("could not get user story")
	ErrCouldNotGetStoryInfo       = errors.New("could not get story info")
	ErrCouldNotDeleteStory        = errors.New("could not delete story")
	ErrStoryNotViewed             = errors.New("story not viewed")
	ErrCouldNotDownloadStory      = errors.New("could not download story")
)
