package errors

import (
	"errors"
)

var (
	ErrLoginFailed                   = errors.New("login failed, incorrect username or password")
	ErrCouldNotGetAPIVersion         = errors.New("could not get API version")
	ErrCouldNotGetSettings           = errors.New("could not get settings")
	ErrCouldNotSetSettings           = errors.New("could not set settings")
	ErrCouldNotGetMediaAuthor        = errors.New("could not get media author")
	ErrCouldNotUploadToStory         = errors.New("could not upload to story")
	ErrCouldNotDownloadVideo         = errors.New("could not download video")
	ErrCouldNotUploadPhoto           = errors.New("could not upload photo")
	ErrCouldNotUnFollowUser          = errors.New("could not unfollow user")
	ErrCouldNotGetUserIdFromUsername = errors.New("could not get user id from username")
	ErrCouldNotGetUsernameFromUserId = errors.New("could not get username from user id")
	ErrCouldNotSeeMedia              = errors.New("could not see media")
	ErrFailedToGetSession            = errors.New("failed to get session")
	ErrFileNotCreated                = errors.New("file not created")
	ErrCouldNotWriteToFile           = errors.New("could not write to file")
	ErrFileDoesNotExist              = errors.New("file does not exist")
	ErrCouldNotReadFile              = errors.New("could not read file")
	ErrCouldNotSetSession            = errors.New("could not set session")
	ErrCouldNotGetFeed               = errors.New("could not get feed")
	ErrCouldNotGetMediaID            = errors.New("could not get media id")
	ErrCouldNotGetMediaPK            = errors.New("could not get media pk")
	ErrCouldNotGetMediaPKFromCode    = errors.New("could not get media pk from code")
	ErrCouldNotGetMediaPKFromURL     = errors.New("could not get media pk from URL")
	ErrCouldNotGetMediaInfoByPk      = errors.New("could not get media info by pk")
	ErrCouldNotGetUserMedias         = errors.New("could not get user medias")
	ErrCouldNotDeleteMedia           = errors.New("could not delete media")
	ErrCouldNotEditMedia             = errors.New("could not edit media")
	ErrAuthorDoesNotExist            = errors.New("could not get media/author")
	ErrCouldNotGetMediaInfo          = errors.New("could not get media info")
	ErrMediaNotLiked                 = errors.New("media not liked")
	ErrMediaCouldNotBeUnliked        = errors.New("media could not be unliked")
	ErrCouldNotGetMediaLikers        = errors.New("could not get media likers")
	ErrCouldNotArchiveMedia          = errors.New("could not archive media")
	ErrCouldNotUnArchiveMedia        = errors.New("could not unarchive media")
	ErrCouldNotGetUserFollowers      = errors.New("could not get user's followers")
	ErrCouldNotGetUsersFollowing     = errors.New("could not get users following")
	ErrCouldNotGetUserInfo           = errors.New("could not get user info")
	ErrCouldNotFollowUser            = errors.New("could not follow user")
	ErrCouldNotUnfollowUser          = errors.New("could not unfollow user")
	ErrCouldNotGetUserId             = errors.New("could not get user ID")
	ErrCouldNotGetUsername           = errors.New("could not get username")
	ErrCouldNotRemoveFollower        = errors.New("could not remove follower")
	ErrCouldNotMutePosts             = errors.New("could not mute posts")
	ErrCouldNotUnmutePosts           = errors.New("could not unmute posts")
	ErrCouldNotMuteStories           = errors.New("could not mute stories")
	ErrCouldNotUnMuteStories         = errors.New("could not unmute stories")
	ErrCouldNotDownloadIgtv          = errors.New("could not download igtv")
	ErrCouldNotGetUserStory          = errors.New("could not get user story")
	ErrCouldNotGetStoryInfo          = errors.New("could not get story info")
	ErrCouldNotDeleteStory           = errors.New("could not delete story")
	ErrStoryNotViewed                = errors.New("story not viewed")
	ErrCouldNotDownloadStory         = errors.New("could not download story")
	ErrCouldNotCreateAbsolutePath    = errors.New("could not create absolute path")
	ErrYamlFileIsEmpty               = errors.New("yaml file is empty")
	ErrCouldNotReadYamlFile          = errors.New("could not read yaml file")
	ErrSettingsFolderNotFound        = errors.New("error settings folder not found")
	ErrCouldNotCreateConfigFiles     = errors.New("could not create configuration files")
	ErrCouldNotReadCookies           = errors.New("could not read cookies")
	ErrCouldNotWriteCookies          = errors.New("could not write cookies")
	ErrCouldNotCreate                = errors.New("could not create")
)
